[project]
name = "ai-agents-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "dotenv>=0.9.9",
    "groq>=0.37.1",
    "ipykernel>=7.1.0",
]
